// Code generated by protoc-gen-tstypes. DO NOT EDIT.

export enum CredentialType {
    UNKNOWN_CREDENTIAL = "UNKNOWN_CREDENTIAL",
    ES256 = "ES256",
    EDDSA = "EDDSA",
    RS256 = "RS256",
}
export interface DeviceInfo {
    path?: string;
    productId?: number;
    vendorId?: number;
    manufacturer?: string;
    product?: string;
}

// Credential ...
export interface Credential {
    id?: Uint8Array;
    authData?: Uint8Array;
    clientDataHash?: Uint8Array;
    type?: CredentialType;
    pubKey?: Uint8Array;
    cert?: Uint8Array;
    sig?: Uint8Array;
    format?: string;
}

export interface DetectDevicesRequest {
}

export interface DetectDevicesResponse {
    devices?: Array<DeviceInfo>;
}

export interface AuthenticatorsService {
    DetectDevices: (r:DetectDevicesRequest) => DetectDevicesResponse;
}
