// Code generated by protoc-gen-tsrpc DO NOT EDIT.
// InputID: b06e29cb3e37cb24010dfe4297aea0af5d1381b3
import {ipcRenderer} from 'electron'
import {randomBytes} from 'crypto'

import {
  DevicesRequest,
  DevicesResponse,
  DeviceInfoRequest,
  DeviceInfoResponse,
  MakeCredentialRequest,
  MakeCredentialResponse,
  SetPINRequest,
  SetPINResponse,
  ResetRequest,
  ResetResponse,
  RetryCountRequest,
  RetryCountResponse,
  AssertionRequest,
  AssertionResponse,
  CredentialsInfoRequest,
  CredentialsInfoResponse,
  CredentialsRequest,
  CredentialsResponse,
  RelyingPartiesRequest,
  RelyingPartiesResponse,
  GenerateHMACSecretRequest,
  GenerateHMACSecretResponse,
  HMACSecretRequest,
  HMACSecretResponse
} from './fido2.d'

export interface RPCError {
    code?: number;
    message?: string;
    details?: string;
}

const replyID = (): string => {
  return randomBytes(20).toString('hex')
}

export type ErrHandler = (err: RPCError) => void
var errHandler: ErrHandler = (err: RPCError) => {}
export const setErrHandler = (eh: ErrHandler) => {
  errHandler = eh
}

export const devices = (
  req: DevicesRequest,
  cb: (err: RPCError, resp: DevicesResponse) => void
) => {
  const reply = 'Auth.Devices-' + replyID()
  ipcRenderer.on(reply, (event, arg) => {
    ipcRenderer.removeAllListeners(reply)
    if (arg.err) {
      console.error('RPC error (Auth.Devices):', arg.err)
      errHandler(arg.err)
    } else {
      console.log('RPC (Auth.Devices) done')
    }
    cb(arg.err, arg.resp)
  })
  console.log('RPC (Auth.Devices)...')
  ipcRenderer.send('rpc', {service: 'Auth', method: 'Devices', args: req, reply: reply})
}

export const deviceInfo = (
  req: DeviceInfoRequest,
  cb: (err: RPCError, resp: DeviceInfoResponse) => void
) => {
  const reply = 'Auth.DeviceInfo-' + replyID()
  ipcRenderer.on(reply, (event, arg) => {
    ipcRenderer.removeAllListeners(reply)
    if (arg.err) {
      console.error('RPC error (Auth.DeviceInfo):', arg.err)
      errHandler(arg.err)
    } else {
      console.log('RPC (Auth.DeviceInfo) done')
    }
    cb(arg.err, arg.resp)
  })
  console.log('RPC (Auth.DeviceInfo)...')
  ipcRenderer.send('rpc', {service: 'Auth', method: 'DeviceInfo', args: req, reply: reply})
}

export const makeCredential = (
  req: MakeCredentialRequest,
  cb: (err: RPCError, resp: MakeCredentialResponse) => void
) => {
  const reply = 'Auth.MakeCredential-' + replyID()
  ipcRenderer.on(reply, (event, arg) => {
    ipcRenderer.removeAllListeners(reply)
    if (arg.err) {
      console.error('RPC error (Auth.MakeCredential):', arg.err)
      errHandler(arg.err)
    } else {
      console.log('RPC (Auth.MakeCredential) done')
    }
    cb(arg.err, arg.resp)
  })
  console.log('RPC (Auth.MakeCredential)...')
  ipcRenderer.send('rpc', {service: 'Auth', method: 'MakeCredential', args: req, reply: reply})
}

export const setPIN = (
  req: SetPINRequest,
  cb: (err: RPCError, resp: SetPINResponse) => void
) => {
  const reply = 'Auth.SetPIN-' + replyID()
  ipcRenderer.on(reply, (event, arg) => {
    ipcRenderer.removeAllListeners(reply)
    if (arg.err) {
      console.error('RPC error (Auth.SetPIN):', arg.err)
      errHandler(arg.err)
    } else {
      console.log('RPC (Auth.SetPIN) done')
    }
    cb(arg.err, arg.resp)
  })
  console.log('RPC (Auth.SetPIN)...')
  ipcRenderer.send('rpc', {service: 'Auth', method: 'SetPIN', args: req, reply: reply})
}

export const reset = (
  req: ResetRequest,
  cb: (err: RPCError, resp: ResetResponse) => void
) => {
  const reply = 'Auth.Reset-' + replyID()
  ipcRenderer.on(reply, (event, arg) => {
    ipcRenderer.removeAllListeners(reply)
    if (arg.err) {
      console.error('RPC error (Auth.Reset):', arg.err)
      errHandler(arg.err)
    } else {
      console.log('RPC (Auth.Reset) done')
    }
    cb(arg.err, arg.resp)
  })
  console.log('RPC (Auth.Reset)...')
  ipcRenderer.send('rpc', {service: 'Auth', method: 'Reset', args: req, reply: reply})
}

export const retryCount = (
  req: RetryCountRequest,
  cb: (err: RPCError, resp: RetryCountResponse) => void
) => {
  const reply = 'Auth.RetryCount-' + replyID()
  ipcRenderer.on(reply, (event, arg) => {
    ipcRenderer.removeAllListeners(reply)
    if (arg.err) {
      console.error('RPC error (Auth.RetryCount):', arg.err)
      errHandler(arg.err)
    } else {
      console.log('RPC (Auth.RetryCount) done')
    }
    cb(arg.err, arg.resp)
  })
  console.log('RPC (Auth.RetryCount)...')
  ipcRenderer.send('rpc', {service: 'Auth', method: 'RetryCount', args: req, reply: reply})
}

export const assertion = (
  req: AssertionRequest,
  cb: (err: RPCError, resp: AssertionResponse) => void
) => {
  const reply = 'Auth.Assertion-' + replyID()
  ipcRenderer.on(reply, (event, arg) => {
    ipcRenderer.removeAllListeners(reply)
    if (arg.err) {
      console.error('RPC error (Auth.Assertion):', arg.err)
      errHandler(arg.err)
    } else {
      console.log('RPC (Auth.Assertion) done')
    }
    cb(arg.err, arg.resp)
  })
  console.log('RPC (Auth.Assertion)...')
  ipcRenderer.send('rpc', {service: 'Auth', method: 'Assertion', args: req, reply: reply})
}

export const credentialsInfo = (
  req: CredentialsInfoRequest,
  cb: (err: RPCError, resp: CredentialsInfoResponse) => void
) => {
  const reply = 'Auth.CredentialsInfo-' + replyID()
  ipcRenderer.on(reply, (event, arg) => {
    ipcRenderer.removeAllListeners(reply)
    if (arg.err) {
      console.error('RPC error (Auth.CredentialsInfo):', arg.err)
      errHandler(arg.err)
    } else {
      console.log('RPC (Auth.CredentialsInfo) done')
    }
    cb(arg.err, arg.resp)
  })
  console.log('RPC (Auth.CredentialsInfo)...')
  ipcRenderer.send('rpc', {service: 'Auth', method: 'CredentialsInfo', args: req, reply: reply})
}

export const credentials = (
  req: CredentialsRequest,
  cb: (err: RPCError, resp: CredentialsResponse) => void
) => {
  const reply = 'Auth.Credentials-' + replyID()
  ipcRenderer.on(reply, (event, arg) => {
    ipcRenderer.removeAllListeners(reply)
    if (arg.err) {
      console.error('RPC error (Auth.Credentials):', arg.err)
      errHandler(arg.err)
    } else {
      console.log('RPC (Auth.Credentials) done')
    }
    cb(arg.err, arg.resp)
  })
  console.log('RPC (Auth.Credentials)...')
  ipcRenderer.send('rpc', {service: 'Auth', method: 'Credentials', args: req, reply: reply})
}

export const relyingParties = (
  req: RelyingPartiesRequest,
  cb: (err: RPCError, resp: RelyingPartiesResponse) => void
) => {
  const reply = 'Auth.RelyingParties-' + replyID()
  ipcRenderer.on(reply, (event, arg) => {
    ipcRenderer.removeAllListeners(reply)
    if (arg.err) {
      console.error('RPC error (Auth.RelyingParties):', arg.err)
      errHandler(arg.err)
    } else {
      console.log('RPC (Auth.RelyingParties) done')
    }
    cb(arg.err, arg.resp)
  })
  console.log('RPC (Auth.RelyingParties)...')
  ipcRenderer.send('rpc', {service: 'Auth', method: 'RelyingParties', args: req, reply: reply})
}

export const generateHMACSecret = (
  req: GenerateHMACSecretRequest,
  cb: (err: RPCError, resp: GenerateHMACSecretResponse) => void
) => {
  const reply = 'Auth.GenerateHMACSecret-' + replyID()
  ipcRenderer.on(reply, (event, arg) => {
    ipcRenderer.removeAllListeners(reply)
    if (arg.err) {
      console.error('RPC error (Auth.GenerateHMACSecret):', arg.err)
      errHandler(arg.err)
    } else {
      console.log('RPC (Auth.GenerateHMACSecret) done')
    }
    cb(arg.err, arg.resp)
  })
  console.log('RPC (Auth.GenerateHMACSecret)...')
  ipcRenderer.send('rpc', {service: 'Auth', method: 'GenerateHMACSecret', args: req, reply: reply})
}

export const hmacSecret = (
  req: HMACSecretRequest,
  cb: (err: RPCError, resp: HMACSecretResponse) => void
) => {
  const reply = 'Auth.HMACSecret-' + replyID()
  ipcRenderer.on(reply, (event, arg) => {
    ipcRenderer.removeAllListeners(reply)
    if (arg.err) {
      console.error('RPC error (Auth.HMACSecret):', arg.err)
      errHandler(arg.err)
    } else {
      console.log('RPC (Auth.HMACSecret) done')
    }
    cb(arg.err, arg.resp)
  })
  console.log('RPC (Auth.HMACSecret)...')
  ipcRenderer.send('rpc', {service: 'Auth', method: 'HMACSecret', args: req, reply: reply})
}

