import {
  Add as AddIcon,
  Album as WormholeIcon,
  ArrowRight as RightArrowIcon,
  ArrowLeft as LeftArrowIcon,
  Assignment as CopyIcon,
  //   Backup as VaultIcon,
  ChevronLeft as BackIcon,
  Close as CloseIcon,
  CreateOutlined as SignIcon,
  CropSquare as MaximizeIcon,
  Crop75 as UnmaximizeIcon,
  EditOutlined as EditIcon,
  EnhancedEncryption as CryptoToolsIcon,
  EnhancedEncryption as EncryptIcon,
  EventNote as NoteIcon,
  LockOpen as DecryptIcon,
  GetApp as ImportIcon,
  Inbox as ChannelsIcon,
  InfoOutlined as InfoIcon,
  Minimize as MinimizeIcon,
  NotInterested as ScreenLockIcon,
  Person as AddRecipientIcon,
  Person as UserIcon,
  PersonAdd as UserLinkIcon,
  //   Policy as AuthnIcon,
  Refresh as RefreshIcon,
  Search as SearchIcon,
  Security as SecretsIcon,
  Settings as SettingsIcon,
  Sync as SyncIcon,
  Visibility as PasswordVisibleIcon,
  VisibilityOutlined as VerifyIcon,
  VpnKeySharp as KeysIcon,
  VpnLock as PasswordIcon,
  Warning as WarningIcon,
} from '@material-ui/icons'

export {
  AddIcon,
  AddRecipientIcon,
  BackIcon,
  ChannelsIcon,
  CloseIcon,
  CopyIcon,
  CryptoToolsIcon,
  DecryptIcon,
  EditIcon,
  EncryptIcon,
  ImportIcon,
  InfoIcon,
  KeysIcon,
  LeftArrowIcon,
  MaximizeIcon,
  MinimizeIcon,
  NoteIcon,
  PasswordIcon,
  PasswordVisibleIcon,
  RefreshIcon,
  RightArrowIcon,
  ScreenLockIcon,
  SearchIcon,
  SecretsIcon,
  SettingsIcon,
  SignIcon,
  SyncIcon,
  UnmaximizeIcon,
  UserIcon,
  UserLinkIcon,
  VerifyIcon,
  WarningIcon,
  WormholeIcon,
}
