import {
  Refresh as RefreshIcon,
  Close as CloseIcon,
  Assignment as CopyIcon,
  PersonAdd as AddRecipientIcon,
  PersonAdd as LinkIcon,
  Sync as SyncIcon,
  Visibility as PasswordVisibleIcon,
  VpnLock as PasswordIcon,
  EventNote as NoteIcon,
  Add as AddIcon,
  EnhancedEncryption as EncryptIcon,
  LockOpen as DecryptIcon,
  CreateOutlined as SignIcon,
  VisibilityOutlined as VerifyIcon,
  ChevronLeft as LeftArrowIcon,
  ArrowRight as RightArrowIcon,
  NotInterested as ScreenLockIcon,
  Minimize as MinimizeIcon,
  CropSquare as MaximizeIcon,
  Crop75 as UnmaximizeIcon,
  VpnKeySharp as KeysIcon,
  Search as SearchIcon,
  EnhancedEncryption as CryptoToolsIcon,
  Settings as SettingsIcon,
  Album as WormholeIcon,
  Security as SecretsIcon,
  //   Policy as AuthnIcon,
  //   Backup as VaultIcon,
} from '@material-ui/icons'

export {
  RefreshIcon,
  CloseIcon,
  CopyIcon,
  AddRecipientIcon,
  LinkIcon,
  SyncIcon,
  PasswordVisibleIcon,
  PasswordIcon,
  NoteIcon,
  AddIcon,
  EncryptIcon,
  DecryptIcon,
  SignIcon,
  VerifyIcon,
  LeftArrowIcon,
  RightArrowIcon,
  ScreenLockIcon,
  MinimizeIcon,
  MaximizeIcon,
  UnmaximizeIcon,
  KeysIcon,
  SearchIcon,
  CryptoToolsIcon,
  SettingsIcon,
  WormholeIcon,
  SecretsIcon,
}
