import {
  Refresh as RefreshIcon,
  Close as CloseIcon,
  Assignment as CopyIcon,
  Person as UserIcon,
  PersonAdd as UserLinkIcon,
  Person as AddRecipientIcon,
  Sync as SyncIcon,
  Visibility as PasswordVisibleIcon,
  VpnLock as PasswordIcon,
  EventNote as NoteIcon,
  Add as AddIcon,
  EnhancedEncryption as EncryptIcon,
  LockOpen as DecryptIcon,
  CreateOutlined as SignIcon,
  VisibilityOutlined as VerifyIcon,
  ChevronLeft as BackIcon,
  ArrowRight as RightArrowIcon,
  ArrowLeft as LeftArrowIcon,
  NotInterested as ScreenLockIcon,
  Minimize as MinimizeIcon,
  CropSquare as MaximizeIcon,
  Crop75 as UnmaximizeIcon,
  VpnKeySharp as KeysIcon,
  Search as SearchIcon,
  EnhancedEncryption as CryptoToolsIcon,
  Settings as SettingsIcon,
  Album as WormholeIcon,
  Security as SecretsIcon,
  //   Policy as AuthnIcon,
  //   Backup as VaultIcon,
  GetApp as ImportIcon,
  EditOutlined as EditIcon,
} from '@material-ui/icons'

export {
  AddIcon,
  AddRecipientIcon,
  BackIcon,
  CloseIcon,
  CopyIcon,
  CryptoToolsIcon,
  DecryptIcon,
  EditIcon,
  EncryptIcon,
  ImportIcon,
  KeysIcon,
  LeftArrowIcon,
  MaximizeIcon,
  MinimizeIcon,
  NoteIcon,
  PasswordIcon,
  PasswordVisibleIcon,
  RefreshIcon,
  RightArrowIcon,
  ScreenLockIcon,
  SearchIcon,
  SecretsIcon,
  SettingsIcon,
  SignIcon,
  SyncIcon,
  UnmaximizeIcon,
  UserIcon,
  UserLinkIcon,
  VerifyIcon,
  WormholeIcon,
}
